apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: lens-metrics
  namespace: gotk-system
spec:
  interval: 1h
  path: ./kustomizations/lens-metrics
  prune: true
  sourceRef:
    kind: GitRepository
    name: gotk-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: nfs-client-provisioner
      namespace: gotk-system

